### PR TITLE
Some quality of life features

### PR DESCRIPTION
**Pull request by dennisklein**
@AndreyLebedev Can you try this on Mac and see if the `launchctl` stuff works (It is all based on docs only, so you may also expect typos and such)?

### CODE REVIEW

**Comment by dennisklein** [comment]
https://www.soma-zone.com/LaunchControl/

**Comment by AndreyLebedev** [comment]
@dennisklein 

1) Why is it really needed to use readline for sample-client? It's just a simple example of a client and it should stay as simple as possible. I think that the use of the external library in this case unnecessary complicates the implementation. In general, I prefer to keep dependencies as small as possible unless it's absolutely necessary.

2) launchctl works on macOS with some minor correction in the config. For some basic testing, I think its fine to use but for production, I would go for a different solution for demonization and logging. The one which we have in DDS I like much more.

**Comment by dennisklein** [comment]
> Why is it really needed to use readline for sample-client?

It is not, but it annoys me the **** when testing. It is just optional as you can see.

> For some basic testing, I think its fine to use but for production ...

In my opinion it is exactly the other way around ;)

**Comment by AndreyLebedev** [comment]
> It is not, but it annoys me the **** when testing. It is just optional as you can see.

What exactly is annoying? Typing the commands? Does shortening of the commands to a  single letter solves your issue? For instance `.init` will have its short conterpart `i`.

> In my opinion it is exactly the other way around ;)

For Linux maybe, but not for macOS.

**Comment by dennisklein** [comment]
Let me try to make some more arguments for `systemd` for testing and production (it is based on `launchd`, so most arguments will hold for it too):

* First of all, why reinvent the wheel on such an important topic. These systems exist exactly for the reason that not every project has to reroll their own broken solution.
* It is used for everything in your operating system and for most system packages. The chances that it is very battle-proven and production-ready are high.
* It has a feature set you can never afford to rebuild in a 2 man project with a different goal.
* It stores, rotates, indexes and compacts the logs in the standard places where I find all my other logs too. And you get it for free, just write to stdout/err. 

Now the killer feature:

```
╭─dklein@gamma ~/projects/DDS-control/build ‹ruby-2.6.0› ‹master›
╰─➤  systemctl --no-pager -l --user status dds-control
● dds-control.service - DDS control server
   Loaded: loaded (/home/dklein/.config/systemd/user/dds-control.service; disabled; vendor preset: enabled)
   Active: active (running) since Sat 2019-07-27 19:15:27 CEST; 53s ago
 Main PID: 20353 (dds-control-ser)
   CGroup: /user.slice/user-1000.slice/user@1000.service/dds-control.service
           ├─20353 /home/dklein/projects/DDS-control/build/install/bin/dds-control-server
           ├─20473 /home/dklein/projects/DDS/build/install/bin/dds-commander --session f1713076-f4f2-43a2-8608-4626df18980f start
           ├─20576 /usr/bin/bash -c /tmp/f1713076-f4f2-43a2-8608-4626df18980f/dds_2019-07-27-19-15-49-543/wn/DDSWorker.sh 12 &> "/tmp/f1713076-f4f2-43a2-8608-4626df18980f/dds_2019-07-27-19-15-49-543/wn/scout.log"
           ├─20585 bash /tmp/f1713076-f4f2-43a2-8608-4626df18980f/dds_2019-07-27-19-15-49-543/wn/DDSWorker.sh 12
           ├─20626 bash /tmp/f1713076-f4f2-43a2-8608-4626df18980f/dds_2019-07-27-19-15-49-543/wn_1/DDSWorker.sh
           ├─20642 bash /tmp/f1713076-f4f2-43a2-8608-4626df18980f/dds_2019-07-27-19-15-49-543/wn_2/DDSWorker.sh
           ├─20660 bash /tmp/f1713076-f4f2-43a2-8608-4626df18980f/dds_2019-07-27-19-15-49-543/wn_3/DDSWorker.sh
           ├─20687 bash /tmp/f1713076-f4f2-43a2-8608-4626df18980f/dds_2019-07-27-19-15-49-543/wn_4/DDSWorker.sh
           ├─20721 bash /tmp/f1713076-f4f2-43a2-8608-4626df18980f/dds_2019-07-27-19-15-49-543/wn_5/DDSWorker.sh
           ├─20756 bash /tmp/f1713076-f4f2-43a2-8608-4626df18980f/dds_2019-07-27-19-15-49-543/wn_6/DDSWorker.sh
           ├─20819 bash /tmp/f1713076-f4f2-43a2-8608-4626df18980f/dds_2019-07-27-19-15-49-543/wn_7/DDSWorker.sh
           ├─20841 /home/dklein/projects/DDS/build/install/bin/dds-agent start
           ├─20895 bash /tmp/f1713076-f4f2-43a2-8608-4626df18980f/dds_2019-07-27-19-15-49-543/wn_8/DDSWorker.sh
           ├─20897 /home/dklein/projects/DDS/build/install/bin/dds-agent start
           ├─20936 /home/dklein/projects/DDS/build/install/bin/dds-agent start
           ├─20959 bash /tmp/f1713076-f4f2-43a2-8608-4626df18980f/dds_2019-07-27-19-15-49-543/wn_9/DDSWorker.sh
           ├─20964 /home/dklein/projects/DDS/build/install/bin/dds-agent start
           ├─21010 bash /tmp/f1713076-f4f2-43a2-8608-4626df18980f/dds_2019-07-27-19-15-49-543/wn_10/DDSWorker.sh
           ├─21030 /home/dklein/projects/DDS/build/install/bin/dds-agent start
           ├─21071 /home/dklein/projects/DDS/build/install/bin/dds-agent start
           ├─21075 bash /tmp/f1713076-f4f2-43a2-8608-4626df18980f/dds_2019-07-27-19-15-49-543/wn_11/DDSWorker.sh
           ├─21096 /home/dklein/projects/DDS/build/install/bin/dds-agent start
           ├─21191 /home/dklein/projects/DDS/build/install/bin/dds-agent start
           ├─21213 /home/dklein/projects/DDS/build/install/bin/dds-agent start
           ├─21216 /home/dklein/projects/DDS/build/install/bin/dds-agent start
           ├─21251 /home/dklein/projects/DDS/build/install/bin/dds-agent start
           ├─21274 /home/dklein/projects/DDS/build/install/bin/dds-agent start
           ├─21283 /home/dklein/projects/FairMQ/build/install/bin/fairmq-ex-dds-processor --id processor_8 --color false --channel-config name=data1,type=pull,method=connect name=data2,type=push,method=connect -P dds
           ├─21284 /home/dklein/projects/FairMQ/build/install/bin/fairmq-ex-dds-sink --id sink --color false --channel-config name=data2,type=pull,method=bind -P dds
           ├─21285 /home/dklein/projects/FairMQ/build/install/bin/fairmq-ex-dds-sampler --id sampler --color false --channel-config name=data1,type=push,method=bind --rate 100 -P dds
           ├─21286 /home/dklein/projects/FairMQ/build/install/bin/fairmq-ex-dds-processor --id processor_1 --color false --channel-config name=data1,type=pull,method=connect name=data2,type=push,method=connect -P dds
           ├─21287 /home/dklein/projects/FairMQ/build/install/bin/fairmq-ex-dds-processor --id processor_5 --color false --channel-config name=data1,type=pull,method=connect name=data2,type=push,method=connect -P dds
           ├─21288 /home/dklein/projects/FairMQ/build/install/bin/fairmq-ex-dds-processor --id processor_9 --color false --channel-config name=data1,type=pull,method=connect name=data2,type=push,method=connect -P dds
           ├─21289 /home/dklein/projects/FairMQ/build/install/bin/fairmq-ex-dds-processor --id processor_3 --color false --channel-config name=data1,type=pull,method=connect name=data2,type=push,method=connect -P dds
           ├─21290 /home/dklein/projects/FairMQ/build/install/bin/fairmq-ex-dds-processor --id processor_2 --color false --channel-config name=data1,type=pull,method=connect name=data2,type=push,method=connect -P dds
           ├─21291 /home/dklein/projects/FairMQ/build/install/bin/fairmq-ex-dds-processor --id processor_0 --color false --channel-config name=data1,type=pull,method=connect name=data2,type=push,method=connect -P dds
           ├─21292 /home/dklein/projects/FairMQ/build/install/bin/fairmq-ex-dds-processor --id processor_6 --color false --channel-config name=data1,type=pull,method=connect name=data2,type=push,method=connect -P dds
           ├─21293 /home/dklein/projects/FairMQ/build/install/bin/fairmq-ex-dds-processor --id processor_7 --color false --channel-config name=data1,type=pull,method=connect name=data2,type=push,method=connect -P dds
           └─21294 /home/dklein/projects/FairMQ/build/install/bin/fairmq-ex-dds-processor --id processor_4 --color false --channel-config name=data1,type=pull,method=connect name=data2,type=push,method=connect -P dds

Jul 27 19:15:50 gamma dds-control-server[20353]: Server reports: 9/12 [10029002003071304663] -> Activated
Jul 27 19:15:50 gamma dds-control-server[20353]: Server reports: 10/12 [5275154993813136955] -> Activated
Jul 27 19:15:50 gamma dds-control-server[20353]: Server reports: 11/12 [6270758021497003067] -> Activated
Jul 27 19:15:50 gamma dds-control-server[20353]: Server reports: 12/12 [2294813168187738709] -> Activated
Jul 27 19:15:50 gamma dds-control-server[20353]: Activated tasks: 12
Jul 27 19:15:50 gamma dds-control-server[20353]: Errors: 0
Jul 27 19:15:50 gamma dds-control-server[20353]: Total: 12
Jul 27 19:15:50 gamma dds-control-server[20353]: Server reports: total: 12, activated: 12, errors: 0
Jul 27 19:15:50 gamma dds-control-server[20353]: Topology activation done
Jul 27 19:15:50 gamma dds-control-server[20353]: Topology activation done successfully
```

It tracks all the process in its own cgroup which means I can always perfectly clean afterwards and will never miss any orphan/rogue processes. I wished DDS would always schedule its commander/agents like this. With a flip of simple switch you get also a watchdog, that is even connected to the hardware watchdog if available.

**Comment by AndreyLebedev** [comment]
@dennisklein Thanks for explanations. I'll look into it in detail.

**Comment by dennisklein** [comment]
Interesting reads:
https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html
https://www.freedesktop.org/software/systemd/man/daemon.html#New-Style%20Daemons

**Pull request closed without merging**
