### PR TITLE
Setup environment automatically

### PR DESCRIPTION
**Pull request by dennisklein**
* Add defaults to command line args
* Add RPATHs

### CODE REVIEW

**Comment by AndreyLebedev** [comment]
@dennisklein I would prefer to use add_custom_command for source file generation. I think it allows better control on parameters. I do not see a big advantage using the built-in macro.

Do you think that proto library is required? Originally I also did it this way but then changed the solution. For simplicity, it was easier to compile source directly in executable. This is anyhow just an example code which has to be as simple as possible.

**Comment by AndreyLebedev** [comment]
@dennisklein DDS env setup we can leave your solution. But in general, we'll have a common solution for DDS in the future.

**Comment by dennisklein** [comment]
With this patch a full cycle works for me reliably, if I wait a few seconds between `.init` and `.config`. If I type them too fast, it fails. We probably need to wait until agents are executing?

> I do not see a big advantage using the built-in macro.

For me it is much more readable.

> For simplicity, it was easier to compile source directly in executable.

Why should I compile them twice? It is not a library, it is an archive, the resulting executable is exactly the same (symbols get copied into each). Also it simplifies configuration, I just link against `dc-proto` which automatically sets up the include paths too.

**Comment by dennisklein** [comment]
> DDS env setup we can leave your solution.

Yes, thats the plan. Hopefully, we can replace this in the future with native DDS API.

---

@AndreyLebedev Notice also the baked in CLI defaults and RPATHS. A simple `cmake ... && cmake --build . --target install` and one can call the executables without the need to setup any PATH or other environment.

**Comment by AndreyLebedev** [comment]
> For me it is much more readable.
True. The only thing which concerns me is that GRPC is not officially supported by cmake. FindGRPC is a code I copied from one of the public repos.

**Comment by dennisklein** [comment]
> FindGRPC is a code I copied from one of the public repos.

This is fine. As long as we keep the copy it will be loaded in preference to any FindGRPC cmake might ship in the future. At that time, we can still bump the required CMake version and remove the local copy. But I doubt they will add it - it would have happened already.

**Comment by dennisklein** [comment]
I mean, in the end, it is your decision which parts you wanna take from this PR. I don't mind, if you only pick it partially.

**Comment by AndreyLebedev** [comment]
@dennisklein I merged it, I'll now test it as well.

**Comment by AndreyLebedev** [comment]
@dennisklein Unfortunately the compilation on macOS is broken now in the GRPC source generation part. I'm trying to figure out why.

**Pull request merged**
